SELECT 
    TABLE_NAME AS '表名',
    COLUMN_NAME AS '字段名',
    COLUMN_TYPE AS '数据类型',
    IS_NULLABLE AS '允许为空',
    COLUMN_KEY AS '键',
    COLUMN_DEFAULT AS '默认值',
    EXTRA AS '额外(自增等)',
    COLUMN_COMMENT AS '注释'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'library_db'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
